stages:
  - build
  - deploy

variables:
  NEXUS_HOST: "http://***REMOVED***:8081"
  NEXUS_REGISTRY: "***REMOVED***:8123"
  RELEASE_ARTIFACT: "packages/wallet-desktop/release"
  NEXUS_IMAGE_TAG: $NEXUS_REGISTRY/auditable-accounting:latest
  URL_DEPLOY_AA: "http://***REMOVED***:19000/api/v2/job_templates/34/launch/"

# build_win:
#   stage: build
#   tags:
#     - "windows"
#   script:
#     - npm i

build_libraries:
  stage: build
  image: node:$NODE_VERSION
  script:
    - cd packages/wallet-protocol
    - npm ci
    - npm run build:js
    - npm run docs
    - npm publish

  rules:
    - if: $CI_COMMIT_TAG != null

## Wallet desktop
build_mac:
  stage: build
  tags:
    - "macos"
  script:
    - npm ci --unsafe-perm
    - npm run pack:mac
  artifacts:
    paths:
      - $RELEASE_ARTIFACT
  rules:
    - if: $CI_COMMIT_TAG != null

build_lin:
  stage: build
  image:
    name: node:14.16.0
  script:
    - npm ci --unsafe-perm
    - npm run pack:lin
  artifacts:
    paths:
      - $RELEASE_ARTIFACT  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master" && $DEPLOY == "true"
  rules:
    - if: $CI_COMMIT_TAG != null

deploy:
  stage: deploy
  image:
    name: peterevans/curl-jq
  script:
    - ./scripts/publish.sh
  # script:
  #   - 'curl --request POST --header "Authorization: Bearer $ANSIBLE_DEPLOY_TOKEN" "$URL_DEPLOY_AA"'
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master" && $DEPLOY == "true"
  rules:
    - if: $CI_COMMIT_TAG != null