stages:
  - build
  - deploy

variables:
  NEXUS_REGISTRY: "***REMOVED***:8123"
  NEXUS_IMAGE_TAG: $NEXUS_REGISTRY/auditable-accounting:latest
  URL_DEPLOY_AA: "http://***REMOVED***:19000/api/v2/job_templates/34/launch/"

build_win:
  stage: build
  tags:
    - "windows"
  script:
    - npm i

# build_lin:
#   stage: build
#   tags:
#     - "linux"
#   script:
#     - npm i

build_lin:
  stage: build
  image:
    name: node:14.16.0
  script:
    - npm i

deploy:
  stage: deploy
  script:
    - ls
    - ls wallet-desktop/
    - ls wallet-desktop/release
  # script:
  #   - 'curl --request POST --header "Authorization: Bearer $ANSIBLE_DEPLOY_TOKEN" "$URL_DEPLOY_AA"'
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master" && $DEPLOY == "true"
