stages:
  - build
  - deploy

variables:
  NEXUS_REGISTRY: "***REMOVED***:8123"
  RELEASE_ARTIFACT: "packages/wallet-desktop/release"
  NEXUS_IMAGE_TAG: $NEXUS_REGISTRY/auditable-accounting:latest
  URL_DEPLOY_AA: "http://95.211.3.249:19000/api/v2/job_templates/34/launch/"

# build_win:
#   stage: build
#   tags:
#     - "windows"
#   script:
#     - npm i

build_mac:
  stage: build
  tags:
    - "shared-macos-amd64"
  script:
    - npm i --unsafe-perm
    - npm run pack:lin
  artifacts:
    paths:
    - $RELEASE_ARTIFACT

build_lin:
  stage: build
  image:
    name: node:14.16.0
  script:
    - npm i --unsafe-perm
    - npm run pack:lin
  artifacts:
    paths:
    - $RELEASE_ARTIFACT

deploy:
  stage: deploy
  script:
    - ls $RELEASE_ARTIFACT
  # script:
  #   - 'curl --request POST --header "Authorization: Bearer $ANSIBLE_DEPLOY_TOKEN" "$URL_DEPLOY_AA"'
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master" && $DEPLOY == "true"
