stages:
  - build
  - deploy

variables:
  NEXUS_HOST: "http://***REMOVED***:8081"
  NEXUS_REGISTRY: "***REMOVED***:8123"
  RELEASE_ARTIFACT: "packages/wallet-desktop/release"
  NEXUS_IMAGE_TAG: $NEXUS_REGISTRY/auditable-accounting:latest
  URL_DEPLOY_AA: "http://***REMOVED***:19000/api/v2/job_templates/34/launch/"

build_libraries:
  stage: build
  image: node:$NODE_VERSION
  script: ./scripts/libraries.sh

  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $DEPLOY_ALL == "true"
    - if: $DEPLOY_LIBRARIES == "true"

## Wallet desktop
build_win:
  stage: build
  tags:
    - "windows"
  script:
    - npm ci --unsafe-perm
    - npm run pack:win

  artifacts:
    paths:
      - $RELEASE_ARTIFACT
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $DEPLOY_ALL == "true"
    - if: $DEPLOY_DESKTOP == "true"
    - if: $DEPLOY_WIN == "true"

build_mac:
  stage: build
  tags:
    - "macos"
  script:
    - npm ci --unsafe-perm
    - npm run pack:mac
  artifacts:
    paths:
      - $RELEASE_ARTIFACT
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $DEPLOY_ALL == "true"
    - if: $DEPLOY_DESKTOP == "true"
    - if: $DEPLOY_MAC == "true"

build_lin:
  stage: build
  image:
    name: node:14.16.0
  script:
    - npm ci --unsafe-perm
    - npm run pack:lin
  artifacts:
    paths:
      - $RELEASE_ARTIFACT
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $DEPLOY_ALL == "true"
    - if: $DEPLOY_DESKTOP == "true"
    - if: $DEPLOY_WIN == "true"

deploy:
  stage: deploy
  image:
    name: peterevans/curl-jq
  script: ./scripts/publish.sh
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $DEPLOY_ALL == "true"
    - if: $DEPLOY_DESKTOP == "true"
    - if: $DEPLOY_WIN == "true"
    - if: $DEPLOY_MAC == "true"
    - if: $DEPLOY_LIN == "true"
