version: '3.6'

services:
  publisher:
    image: peterevans/curl-jq
    container_name: wallet-publisher
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    command:
      - /app/scripts/publish.sh

  libraries:
    image: node:16
    container_name: wallet-libraries
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    command:
      - /app/scripts/libraries.sh
