version: '3.6'

services:
  publisher:
    image: peterevans/curl-jq
    container_name: wallet-publisher
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    command:
      - /app/scripts/publish.sh