name: publish

on:
  workflow_dispatch:

jobs:
  publication:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [14.17]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Install root dependecies
        run: npm ci

      - name: Install desktop dependecies
        run: npm run install:desktop

      - name: Build desktop
        run: npm run build:desktop

      - name: build linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run pack:lin

      - name: build windows
        if: matrix.os == 'windows-latest'
        run: npm run pack:win

      - name: build macos
        if: matrix.os == 'macos-latest'
        run: npm run pack:mac

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          release_name: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./packages/wallet-desktop/release/wallet-desktop-${{ steps.branch_name.outputs.SOURCE_TAG }}-amd64.deb
          asset_name: wallet-desktop-${{ steps.branch_name.outputs.SOURCE_TAG }}-amd64.deb
          asset_content_type: application/zip

      - name: Upload Release Asset
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./packages/wallet-desktop/release/wallet-desktop-${{ github.ref }}-x86_64.AppImage
          asset_name: wallet-desktop-${{ steps.branch_name.outputs.SOURCE_TAG }}-x86_64.AppImage
          asset_content_type: application/zip
